apiVersion: v1
kind: Service
metadata:
  name: postgres-transactions-service
  namespace: zamazon
spec:
  selector:
    app: postgres-transactions
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432