auth:
  enabled: true
  rootPassword: "1234"
  existingSecret: ""
architecture: replicaset
replicaCount: 1       # Use only one replica
# Optionally, disable the arbiter if supported:
arbiter:
  enabled: false

persistence:
  enabled: true
  size: 1Gi           # Use a smaller size for testing
volumePermissions:
  enabled: true
metrics:
  enabled: false
  prometheusRule:
    enabled: false

image:
  registry: ghcr.io/zcube
  repository: bitnami-compat/mongodb
  tag: 6.0.5

# Optionally, you might need to override other configuration if the ARM image layout differs.