apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  namespace: zamazon
spec:
  replicas: 3
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z postgres-user-service 5432; do echo "Waiting for postgres..."; sleep 2; done;
              echo "Postgres is listening; waiting an extra 10 seconds for full readiness...";
              sleep 10;
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
      containers:
        - name: users
          image: sharat789/zamazon-be-ms-users:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: users-env-config