apiVersion: v1
kind: Service
metadata:
  name: postgres-catalog-service
  namespace: zamazon
spec:
  selector:
    app: postgres-catalog
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432