apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: zamazon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: sharat789/zamazon-be-ms-auth:latest
          ports:
            - containerPort: 8080
              name: metrics
          envFrom:
            - configMapRef:
                name: auth-env-config