apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-service-monitor
  namespace: monitoring  # Deploy in same namespace as Prometheus
  labels:
    release: prometheus-stack  # Match Prometheus' default selector
spec:
  selector:
    matchLabels:
      app: auth  # Must match users-service labels
  namespaceSelector:
    matchNames:
      - zamazon  # Where your service lives
  endpoints:
    - port: metrics  # Must match Service port name
      interval: 15s
      path: /metrics